// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDv6cNnR5_kOBbtJKxCYqUQd8eatN0bEI',
    appId: '1:288378422483:web:ab212ef9f9c0fc34560026',
    messagingSenderId: '288378422483',
    projectId: 'payment-d1e41',
    authDomain: 'payment-d1e41.firebaseapp.com',
    storageBucket: 'payment-d1e41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaSbVJ8t-mCAORsz2HB-x3aeRHBtaStw',
    appId: '1:288378422483:android:a4b76ab1843b7279560026',
    messagingSenderId: '288378422483',
    projectId: 'payment-d1e41',
    storageBucket: 'payment-d1e41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56_ekaF6PcjNYPBQYnCvSA7VTRq-zgKY',
    appId: '1:288378422483:ios:1edc3f930a1946d0560026',
    messagingSenderId: '288378422483',
    projectId: 'payment-d1e41',
    storageBucket: 'payment-d1e41.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56_ekaF6PcjNYPBQYnCvSA7VTRq-zgKY',
    appId: '1:288378422483:ios:43a7749041226a1d560026',
    messagingSenderId: '288378422483',
    projectId: 'payment-d1e41',
    storageBucket: 'payment-d1e41.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
